# -*- coding: utf-8 -*-
"""Sistemas Inteligentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5CT9-jeZCDQn6AznjSrdWG-cAmhK_bQ
"""

nombre=input("Introduce tu nombre: ")

numero=int(input("Introduce un número: "))
print("Te llamas:"+nombre+" y tu número es el "+str(numero))

"""# Primer ejemplo Python"""

numero = 1
while numero < 5:
  print(numero)
  numero+=1

import random
numeroR = random.randint(1,10)

print(numeroR)

num1=int(input("Introduce el primer número: "))
num2=int(input("Introduce el segundo número: "))
opcion = 0
print("Introduce una opción\n1-Sumar\n2-Restar")
opcion=int(input())
if opcion==1:
    print("La suma es:",num1+num2)
# print("La suma es:"+str(num1+num2))
elif opcion==2:
    print("La resta es:",num1-num2)
else:
    print("Opción incorrecta")

import random
intentosRealizados = 0
estimacion = 0

print('Hola, Como te llamas?')
miNombre = input()

print('\n¿Quieres jugar en modo "campeonato" (3 intentos) o "normal" (5 intentos)? (Escribe "campeonato" o "normal")')
modo_juego = input().lower()

if modo_juego == 'campeonato':
    max_intentos = 3
    print(f'\n¡{miNombre}, estás jugando en modo campeonato! Tienes {max_intentos} intentos para adivinar el número entre 1 y 50.')
elif modo_juego == 'normal':
    max_intentos = 5
    print(f'\n¡{miNombre}, estás jugando en modo normal! Tienes {max_intentos} intentos para adivinar el número entre 1 y 50.')
else:
    print('\nOpción de juego no reconocida. Se establecerá el modo normal (5 intentos) por defecto.')
    max_intentos = 5
    print(f'¡{miNombre}, estás jugando en modo normal! Tienes {max_intentos} intentos para adivinar el número entre 1 y 50.')

numero = random.randint(1, 50)

while intentosRealizados < max_intentos:
    print('\nIntenta adivinarlo, dime un número:')
    estimacion_str = input()
    try:
        estimacion = int(estimacion_str)
    except ValueError:
        print('Por favor, introduce un número válido.')
        continue # Pide de nuevo la entrada sin contar este intento

    intentosRealizados = intentosRealizados + 1

    if estimacion < numero:
        print('Es mayor')
    elif estimacion > numero:
        print('Es menor')
    else: # Si estimacion == numero, ha adivinado
        break # Sale del bucle, ya que ha adivinado

# Verifica el resultado después del bucle
if estimacion == numero:
    print(f'\n¡Muy bien, {miNombre}! Has adivinado mi número ({numero}) en {intentosRealizados} intentos.')
else:
    print(f'\nLo siento, {miNombre}. No has adivinado mi número en {max_intentos} intentos.')
    print(f'El número que estaba pensando era el {numero}.')
    if modo_juego == 'campeonato':
        print('¡La máquina ha ganado el campeonato!')
    else:
        print('¡Mejor suerte la próxima vez!')

import random

print("¡Vamos a jugar a Piedra, Papel o Tijera!")

lista_opciones = ['Piedra', 'Papel', 'Tijera']

print("Elige una opción: Piedra, Papel o Tijera")
eleccion_usuario = input()
eleccion_usuario = eleccion_usuario.capitalize()


if eleccion_usuario not in lista_opciones:
    print("¡Esa no es una opción válida! Por favor, escribe Piedra, Papel o Tijera.")
else:

    eleccion_computadora = random.choice(lista_opciones)

    print("Tú elegiste: " + eleccion_usuario)
    print("La computadora eligió: " + eleccion_computadora)

    if eleccion_usuario == eleccion_computadora:
        print("¡Es un empate!")
    elif eleccion_usuario == 'Piedra' and eleccion_computadora == 'Tijera':
        print("¡Tú ganas!")
    elif eleccion_usuario == 'Papel' and eleccion_computadora == 'Piedra':
        print("¡Tú ganas!")
    elif eleccion_usuario == 'Tijera' and eleccion_computadora == 'Papel':
        print("¡Tú ganas!")
    else:
        print("¡La computadora gana!")

import numpy as np
x = np.array([[0.45, 0.40],[0.10, 0.45],[0.80, 0.60],[0.60, 0.75]])
t = np.array([0, 0, 1, 1])
#comprobamos
x[0]
t[0]
#Definimos muestras y entradas
muestras=np.size(x,0)
entradas=np.size(x,1)
print("Muestras: %d - Entradas: %d\n" %(muestras,entradas))

#Semilla
np.random.seed(1)
w = np.random.rand(entradas)
b= np.random.rand()
#Vemos los valores aleatorios para w y b

w

b

def y(entrada):
    if (np.dot(entrada, w) + b) > 0:
      salida = 1
    else:
      salida = 0
    return salida
#Probamos la salida de la neurona
y(np.array([0.2, 0.3]))

#Otra forma…
y(x[1])

#Entrenando a la neurona
epocas=20
for epoca_actual in range(1,epocas+1):
  aciertos=0
for muestra_actual in range(0,muestras):
  prediccion=y(x[muestra_actual])
objetivo=t[muestra_actual]
print("Época:",epoca_actual,"Muestra:", muestra_actual,"Obj:",objetivo,"Pred:",prediccion,"\n")
error=objetivo-prediccion
w += error * x[muestra_actual]
b += error
if (objetivo==prediccion):
  aciertos+=1
acc=aciertos/muestras
print("Prob.Acierto:",acc,"\n")

#Entrenando a la neurona
epocas=20
u=0.01
lista_aciertos=[]
for epoca_actual in range(1,epocas+1):
  aciertos=0
for muestra_actual in range(0,muestras):
  prediccion=y(x[muestra_actual])
objetivo=t[muestra_actual]
print("Época:",epoca_actual,"Muestra:", muestra_actual,"Obj:",objetivo,"Pred:",prediccion,"\n")
error=objetivo-prediccion
w += u*error * x[muestra_actual]
b += u*error
if (objetivo==prediccion):
  aciertos+=1
acc=aciertos/muestras
print("Prob.Acierto:",acc,"\n")
lista_aciertos.append(acc)

#Comprobamos los valores finales de w y b.
w
b
#Predicción para una nueva entrada…
y(np.array([0.3, 0.2]))

import matplotlib.pyplot as plt
plt.plot(lista_aciertos) #plt.plot(range(1,epocas+1),lista_aciertos)
plt.xlabel('Épocas')
plt.ylabel('ACC')
plt.show()